# Generated by Django 6.0.6 on 2026-06-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('craft', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('monthly_income', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('caste_category', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('BC', 'Backward Class'), ('General', 'General')], default='General', max_length=10)),
                ('language', models.CharField(default='tamil', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producers',
                'ordering': ['-created_at'],
            },
        ),
    ]
