# Generated by Django 6.0.6 on 2026-06-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('benefit', models.TextField()),
                ('eligibility', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('documents_required', models.TextField(blank=True)),
                ('applicable_crafts', models.TextField(blank=True)),
                ('applicable_districts', models.TextField(blank=True)),
                ('caste_eligibility', models.CharField(choices=[('all', 'All Categories'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('SC_ST', 'SC / ST'), ('OBC', 'Other Backward Class')], default='all', max_length=10)),
                ('min_income', models.PositiveIntegerField(blank=True, null=True)),
                ('max_income', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_path', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True)),
                ('detected_language', models.CharField(default='tamil', max_length=50)),
                ('matched_schemes', models.JSONField(blank=True, default=list)),
                ('recommended_platforms', models.JSONField(blank=True, default=list)),
                ('listing_tamil', models.TextField(blank=True)),
                ('listing_english', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('transcribed', 'Transcribed'), ('matched', 'Schemes Matched'), ('listing_generated', 'Listing Generated'), ('completed', 'Completed'), ('failed', 'Failed')], default='transcribed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='producers.producer')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
